version: "3.7"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  postgres-ui:
    image: dpage/pgadmin4:6.5
    links:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@acme.com #the username to login to pgadmin
      PGADMIN_DEFAULT_PASSWORD: pgadmin # the password to login to pgadmin
      PGADMIN_CONFIG_SERVER_MODE: 'False' # True for production, False for development
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False' # True for production, False for development
    volumes:
      - ./compose/pgadmin/servers.json:/pgadmin4/servers.json # preconfigured servers/connections
      - ./compose/pgadmin/pgpass:/pgpass # passwords for the connections in this file